spring:
  application:
    name: GroceryListApp
    jwtSecret: ${jwtSecret}
    jwtExpirationMs: ${jwtExpiration}
  data:
    mongodb:
      uri: ${mongoUrl}
frontend:
  url: http://localhost:3000
#logging:
#  level:
#    root: DEBUG